Add blogpost on gender data
technologiestiftung/odis-website pull request #106
Opened 2022-02-22 09:13 UTC by ester-t-s

2022-03-07 13:52 UTC, ff6347 requested changes

2022-03-07 13:52 UTC, ff6347 commented on source/_posts/aktuelles/2022-03-03-gender_data_gap.md
> +layout: news
To prepare for the upcoming migration you need to add 

```yml
tags: post
```

to your frontamatter

2022-03-09 09:34 UTC, Lisa-Stubert approved these changes

2022-07-05 12:56 UTC, ester-t-s commented
WIP

2022-08-22 07:30 UTC, closed without merging