add project description and images
technologiestiftung/odis-website pull request #110
Opened 2022-03-07 10:02 UTC by ester-t-s

2022-03-07 13:34 UTC, ff6347 commented on source/projekte/organigramme/guide.md
>  <center>{% include macro-image-section-small.html src="images/step3.png"%}</center>
Hi @ester-t-s I did the migration from jekyll to 11ty in #109 the include you use here will fail. You need to quote the include file name. So 

```
% include macro-image-section-small.html src="images/step3.png"%}
```

should be

```
% include "macro-image-section-small.html" src="images/step3.png"%}
```

2022-03-07 13:53 UTC, ff6347 requested changes

2022-03-07 13:53 UTC, ff6347 commented on source/projekte/organigramme/index.md
>  layout: project
To prepare for the upcoming migration you need to add 

```
tags: post
```
to your frontmatter

2022-03-09 09:37 UTC, Lisa-Stubert approved these changes

2022-03-09 09:38 UTC, Lisa-Stubert submitted a review, later dismissed

2022-03-10 19:45 UTC, ff6347 requested changes

2022-07-28 12:45 UTC, merged