Feat/implement homepage
technologiestiftung/odis-website pull request #262
Opened 2023-08-29 11:41 UTC by raphael-arce

This is a first draft of the homepage. It still lacks the puzzle map and the module slider.

2023-08-29 12:50 UTC, vogelino requested changes
Good work! I added a few comments about the use of primitive colors and arbitiary colors. Other than that it LGTM. Thx!

2023-08-29 12:50 UTC, vogelino commented on source/index.liquid
> +        {% render 'button', text: 'Newsletter Abonnieren' %}
How does this work? In the button component the prop is called `tag` and here it is `render` but the button component hasn't been changed. Is it a liquid-specific thing?

2023-08-29 12:50 UTC, vogelino commented on source/index.liquid
> +          <div class="text-[4.5rem] font-bold text-[var(--white)] text-stroke-2 text-stroke-blue">
IMO it is ok to use the closest tailwind font-size here instead of using arbitrary values. Also, the text class can simply be `text-bg` as it shares the same color than the background. Also, as stated in teh tailwind config file, please use the semantic colors instead of the primitives. Here, `text-stroke-blue` should be `text-stroke-line`. This applies everywhere.

2023-08-29 12:53 UTC, raphael-arce commented on source/index.liquid
> +        {% render 'button', text: 'Newsletter Abonnieren' %}
I'm not sure if I understand what you mean, but here I used `render` instead of `include` as it is deprecated: https://shopify.dev/docs/api/liquid/tags/include

2023-08-29 13:51 UTC, vogelino commented on source/index.liquid
> +        {% render 'button', text: 'Newsletter Abonnieren' %}
Ah ok sorry my question was confusing. I didn't know it was deprecated. Thx for clarifying!

2023-08-29 13:53 UTC, raphael-arce commented on source/index.liquid
> +          <div class="text-[4.5rem] font-bold text-[var(--white)] text-stroke-2 text-stroke-blue">
Okay, will do 👍

2023-08-29 15:13 UTC, raphael-arce commented on source/index.liquid
> +          <div class="text-[4.5rem] font-bold text-[var(--white)] text-stroke-2 text-stroke-blue">
@vogelino I have updated all arbitrary values I have found, could you maybe have another look?

2023-08-30 07:51 UTC, dnsos requested changes
Good work! I've got a few comments and I would suggest to already add some better styling for mobile sizes. Nothing sophisticated, just some basic styles so that content is properly visible and padded on smaller screens.

2023-08-30 07:51 UTC, dnsos commented on source/assets/css/tailwind.css
> +  .text-stroke-2 {
Tailwind [recommends](https://tailwindcss.com/docs/adding-custom-styles#adding-custom-utilities) putting custom utility classes in the `@utilities` directive.

2023-08-30 07:51 UTC, dnsos commented on source/index.liquid
> +  <div class="bg-cyan-100 flex justify-center py-60 -mt-60 -mb-40 -z-10">
Does this class still exist with the new color scheme?

2023-08-30 07:51 UTC, dnsos commented on source/index.liquid
> +          {% comment %} Note: the classes text-stroke-xy is not part of tailwind {% endcomment %}
By adding it as a utility class (see comment above) it essentially becomes part of (our) Tailwind. I would suggest to remove this comment and the ones some lines down.

2023-08-30 07:51 UTC, dnsos commented on source/index.liquid
> +            <div class="w-full border-t-[0.5rem] border-t-line"></div>
Here's still an arbitrary class. I'd suggest we sync this with the text link border width (in this case this would become `border-t-8`.)

Also, instead of having this as it's own decorative element how about adding a `border-b-8` to the wrapping `div`?

2023-08-30 07:51 UTC, dnsos commented on source/index.liquid
> +    <div class="col-start-4 col-span-6 flex flex-col gap-8">
This doesn't work very well on smaller screens. How about changing the `col-start-` and `col-span-` values so that the content has more horizontal space?

2023-08-30 09:07 UTC, raphael-arce commented on source/index.liquid
> +  <div class="bg-cyan-100 flex justify-center py-60 -mt-60 -mb-40 -z-10">
Good point. I actually tried to not touch this part, as the designs were not ready yet. But it looks like I added this in the beginning and forgot to remove it. I'll remove it 👍

2023-08-30 09:10 UTC, raphael-arce commented on source/assets/css/tailwind.css
> +  .text-stroke-2 {
Okay will do 👍

2023-08-30 09:10 UTC, raphael-arce commented on source/index.liquid
> +          {% comment %} Note: the classes text-stroke-xy is not part of tailwind {% endcomment %}
Okay. The motivation behind this comment was to give a heads up that if somebody tries some other classes like `text-stroke-4`, `text-stroke-6` it won't work. But if this will never happen, I can remove it 👍

2023-08-30 09:13 UTC, raphael-arce commented on source/index.liquid
> +            <div class="w-full border-t-[0.5rem] border-t-line"></div>
That a good point, will do 👍

2023-08-30 09:16 UTC, dnsos commented on source/index.liquid
> +          {% comment %} Note: the classes text-stroke-xy is not part of tailwind {% endcomment %}
Ahh, I see! I find Tailwind works best with some tooling around it ([for VSCode](https://tailwindcss.com/docs/editor-setup#intelli-sense-for-vs-code), [for JetBrains products](https://tailwindcss.com/docs/editor-setup#jet-brains-ides)). Ideally this tooling takes care of the available classes. But of course this is not available in every environment, so I understand your general motivation.

2023-08-30 09:29 UTC, raphael-arce commented on source/index.liquid
> +    <div class="col-start-4 col-span-6 flex flex-col gap-8">
I agree, but I think I would need a directive on mobile layout from you or @vogelino, rather than taking a decision on my own. I mean, from the top of my head, we could do a `col-start-2 col-span-10 lg:col-start-4 lg:col-span-6`, which would look like this:

https://github.com/technologiestiftung/odis-website/assets/8709861/0c23d62c-c63c-46c5-b271-a35181f83acb

but Idk if that fits with the rest of the design system 😄

2023-08-30 09:43 UTC, dnsos commented on source/index.liquid
> +    <div class="col-start-4 col-span-6 flex flex-col gap-8">
> from the top of my head

That's a great solution for just from the top the head! 😄👍 

If you have time for adding some simple (not necessarily perfect) mobile styles, I would encourage that! We can also fine-tune later, but having some sane basics seems totally valuable to me.

2023-08-30 09:51 UTC, vogelino commented on source/index.liquid
> +    <div class="col-start-4 col-span-6 flex flex-col gap-8">
Agree with @dnsos. Let's start with the best possible solution based on the design and improvise the rest. We can fine-tune the rest later on.

2023-08-30 09:51 UTC, vogelino approved these changes

2023-08-30 11:09 UTC, raphael-arce commented
@dnsos I have implemented all your suggestions, let me know what you think about it!

2023-08-30 13:21 UTC, dnsos approved these changes
Great work, that's a very solid responsiveness!

2023-08-30 13:25 UTC, raphael-arce commented on source/assets/css/tailwind.css
> +  .text-stroke-2 {
I also have no idea why it did not work you for @vogelino, in my case it worked!

2023-08-30 13:25 UTC, merged