Feat/implement footer
technologiestiftung/odis-website pull request #264
Opened 2023-08-31 08:01 UTC by raphael-arce

Implemented the new footer

2023-08-31 08:48 UTC, vogelino requested changes
Thx! Good work. I have a few comments below:

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +  <div class="col-start-2 col-span-10 border-t-4 border-t-line"></div>
Why not use a border top instead of introducing another element into the DOM?

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +  <div class="col-start-2 col-span-10 border-t-4 border-t-line"></div>
I would make sure the footer's max width corresponds with the one used in other pages using the `container max-w-6xl` classes on the container. (you couldn't know at this stage but now you do 😉 )

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +        <img
I think the icons in the footer (And I think the same about the logos but we already discussed that) should be added as SVG liquid components, this way you can change their color on hover, focus or dark mode.

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +        <img
I think you are missing focus and hover styles everywhere. Make sure to add that otherwise there is no visual feedback when using the mouse or keyboard. For the logos, you can decrease the opacity of sibling logos on hover as to highlight the currently hovered one. As for focus styles, look into the button or text-link component for inspiration!

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +    <p class="max-w-md text-sm">
This text shouldn't be smaller. In the designs, it shares the same font size as other paragraphs. You could use the new `paragraph` partial created recently. It would look like:

```liquid
{% render 'paragraph', text: 'Ein Projekt...' %}
```

2023-08-31 08:48 UTC, vogelino commented on source/_includes/footer.html
> +        <img
See this screenshot with dark mode as an illustration of this problem:

![Screenshot 2023-08-31 at 10 46 48](https://github.com/technologiestiftung/odis-website/assets/2759340/185f1450-98ad-4476-acdf-94de4a2b3cba)

2023-08-31 09:26 UTC, raphael-arce commented on source/_includes/footer.html
> +  <div class="col-start-2 col-span-10 border-t-4 border-t-line"></div>
I used for the logos+paragraph and social media icons+outlinks different grid components. Using a border top would be split in that case:

![Bildschirmfoto 2023-08-31 um 11 23 15](https://github.com/technologiestiftung/odis-website/assets/8709861/29ff9c29-4e02-400b-a60d-07acbdf1211b)

I have to admit I'm not very experience with grids and it might not be the ideal approach. I'd be curious to know if there is an easier/better way!


> I would make sure the footer's max width corresponds with the one used in other pages using the `container max-w-6xl` classes on the container. (you couldn't know at this stage but now you do 😉 )

Alright! will do 👍

2023-08-31 09:34 UTC, raphael-arce commented on source/_includes/footer.html
> +        <img
I was not aware we already had a dark mode. And good point regarding hover, focus states, I have not thought about that. But with all that coming together, I agree, using liquid components would probably be better. will change 👍

2023-08-31 09:42 UTC, raphael-arce commented on source/_includes/footer.html
> +        <img
I have to admit I'm a bit unsure how to style all those interactions. But I'll give it a try 👍

2023-08-31 09:42 UTC, raphael-arce commented on source/_includes/footer.html
> +    <p class="max-w-md text-sm">
ah good point. will do! 👍

2023-08-31 10:34 UTC, vogelino commented on source/_includes/footer.html
> +  <div class="col-start-2 col-span-10 border-t-4 border-t-line"></div>
You woud add the border top to the container and not to the grid item.

2023-08-31 10:35 UTC, vogelino commented on source/_includes/footer.html
> +        <img
We don't have a the toggle yet but the design system is already built to support dark mode, so the code should support recoloring ui elements resp.

2023-08-31 13:19 UTC, raphael-arce commented on source/_includes/footer.html
> +        <img
I updated as you suggested but we still have an issue with the facebook and github icon. Currently the `f` is cut and cannot be styled with another colour than the background. 


![Bildschirmfoto 2023-08-31 um 15 16 46](https://github.com/technologiestiftung/odis-website/assets/8709861/d10fb1ff-406f-4caa-9562-b3a7938d73ad)


But if you use a backgroundColor on the SVG, it will look like this:

![Bildschirmfoto 2023-08-31 um 15 19 06](https://github.com/technologiestiftung/odis-website/assets/8709861/a7fe5909-4656-4a3c-a66c-2bb2bda48bb7)

2023-08-31 14:51 UTC, vogelino commented on source/_includes/footer.html
> +        <img
Your focus styles are fine, however I prefer when the focus ring "hugs" the focused element. For example, you could add a `rounded-full` class to the icon in order for the focus ring to be in the same shape as the elements it contains (in this case round). Finally, for such small items, I think 8 is a little too big of an offset. I'd rather go with 4. But it is a matter of preference here. Feel free to ignore :)

2023-08-31 14:53 UTC, vogelino commented on source/_includes/footer.liquid
> +    <div class="flex flex-col md:flex-row gap-3 items-center">
Using `items-center` here doesn't look too good on mobile (See screenshot below). I'd rather have them _flow_ like regular text.

![Screenshot 2023-08-31 at 16 51 34](https://github.com/technologiestiftung/odis-website/assets/2759340/d085147a-6a44-43c8-afdc-02cd8bd5d5b9)

2023-08-31 14:54 UTC, vogelino commented on source/_includes/footer.liquid
> +    <div class="flex flex-col md:flex-row gap-3 items-center">
Using `flex-wrap` and `flex-row`:

![Screenshot 2023-08-31 at 16 53 56](https://github.com/technologiestiftung/odis-website/assets/2759340/ad58e620-d75b-4a4b-a793-b87877fc6261)

2023-08-31 14:55 UTC, vogelino commented on source/_includes/footer.liquid
> +    <div class="flex flex-col md:flex-row gap-3 items-center">
PS: We should replace the twitter logo with the X logo.

2023-09-01 09:05 UTC, raphael-arce commented on source/_includes/footer.liquid
> +    <div class="flex flex-col md:flex-row gap-3 items-center">
yes that's true. thanks! 👍

2023-09-01 12:25 UTC, raphael-arce commented
@vogelino I've updated everything, would you mind having another look? Thanks 🙏

2023-09-15 13:25 UTC, dnsos approved these changes

2023-09-15 13:25 UTC, merged